<!DOCTYPE html>
<html lang="en"> 
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>3D Details &amp; Illustrations - GB Group Marketing Tools &amp; Brand Assets - Grégoire Besson, Rabe, Agriway</title>
    <meta name="description" content="">
    <meta name="author" content="GB Group">

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700&amp;subset=cyrillic,cyrillic-ext,latin-ext|Kanit:500" rel="stylesheet">
    <link href="../../../css/bootstrap.min.css" rel="stylesheet">
    <link href="../../../css/style.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-108104860-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-108104860-7');
    </script>

  </head>
  <body>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <a href="https://marketing.gb-group.co">Back to homepage</a>
                <br>
                <br>
                <h1>3D Details &amp; Illustrations</h1>
                <br>
                <div class="row">
                    <?php
                    $arr = array(
                    "charrues-non-stop-hydraulique-2.png",
                    "charrues-non-stop-hydraulique.png",
                    "charrues-securite-boulon-sols-legers.png",
                    "charrues-securite-boulon.png",
                    "charrues-selecteur-hydraulique.jpg",
                    "charrues-vanne-tarrage-1.png",
                    "charrues-vanne-tarrage-2.png",
                    "cover-explor-discordon-palier-usine-1.png",
                    "cover-explor-discordon-palier-usine-2.png",
                    "cover-explor-discordon-palier.png",
                    "cover-v-t50.png",
                    "cover-v-t60.png",
                    "cover-v-t70.png",
                    "cover-x-t50.png",
                    "cover-x-t60-1-arbre.png",
                    "cover-x-t60-2-arbre.png",
                    "cover-x-t60.png",
                    "cover-x-t70.png",
                    "cover-x-t80.png",
                    "cover-xl-t50.png",
                    "cover-xl-t60.png",
                    "cover-xl-t70.png",
                    "cover-xl-t80.png",
                    "cover-xl-t90.png",
                    "crossland-50.png",
                    "crossland-60-1.png",
                    "crossland-60-2.png",
                    "crossland-60-3.png",
                    "crossland-60-4.png",
                    "crossland-60-571945-457044.png",
                    "crossland-60.png",
                    "crossland-boulon.png",
                    "crossland-dent-queue-cochon.png",
                    "crossland-disque-niveleur.png",
                    "crossland-ecrou-bloque.png",
                    "crossland-etancon-reglable.jpg",
                    "crossland-etancon.png",
                    "crossland-eurochisel-reversible.png",
                    "crossland-gamme-pointes.png",
                    "crossland-gamme-pointes2.png",
                    "crossland-pas-230.jpg",
                    "crossland-protection-de-vis-etancon.png",
                    "crossland-queue-cochon-profil.png",
                    "crossland-queue-cochon.png",
                    "crossland-schema-sol.png",
                    "crossland-securite-boulon.png",
                    "crossland-t60-571912-438448.png",
                    "crossland-t60-571912-469348.png",
                    "crossland-t70.png",
                    "crossland-t80-plat.png",
                    "crossland-t80-plie.png",
                    "crossland-vis-presicaillee.png",
                    "crossland-vis-teton.png",
                    "discordon-60.png",
                    "discordon-chassis-2-niveaux.png",
                    "discordon-dents.png",
                    "discordon-elastomere-1.png",
                    "discordon-elastomere-2.png",
                    "discordon-premiers-disques.png",
                    "discordon-profondeur-travail-dents.png",
                    "discordon-rouleaux.png",
                    "discordon-seconds-disques.png",
                    "discordon-securite-boulon.png",
                    "discordon-securite-hydraulique.png",
                    "discordon-t70.png",
                    "discordon-t80.png",
                    "discordon-tirant-angle-trains-disques-discordon.png",
                    "discordon-trains-de-disques-decales-1.png",
                    "discordon-trains-de-disques-decales-2.png",
                    "explor-accumulateur-azote-1.png",
                    "explor-accumulateur-azote-2.png",
                    "explor-carter-blinde-explor-1.png",
                    "explor-cle-de-serrage-embarquee.png",
                    "explor-disque-fleau.png",
                    "explor-palier-usine-2.png",
                    "explor-palier.png",
                    "explor-poutre-a-toutes-epreuves.png",
                    "explor-reglage-angle-de-fleche-1.png",
                    "explor-reglage-angle-de-fleche-2.png",
                    "explor-securite-elastomere-explor-1.png",
                    "explor-securite-elastomere-explor-2.png",
                    "explor-t70-1.png",
                    "explor-t70-2.png",
                    "explor-t70-3.png",
                    "explor-t70-4.png",
                    "explor-t70-5.png",
                    "explor-t70-6.png",
                    "explor-t70-7.png",
                    "explor-t70.png",
                    "explor-t80.png",
                    "explor-t90-2.png",
                    "explor-t90-3.png",
                    "explor-t90-4.png",
                    "explor-t90-5.png",
                    "explor-t90-6.png",
                    "explor-t90-7.png",
                    "explor-t90-8.png",
                    "explor-t90.png",
                    "explor-terrage-possible-par-les-roues.png",
                    "explor-tirant-reglage-simple-angle-trains-disques-1.png",
                    "explor-tirant-reglage-simple-angle-trains-disques-2.png",
                    "explor-trains-de-disques-solides.png",
                    "helios-01-restructuration-profonde.png",
                    "helios-02-decompaction-intermediaire.png",
                    "helios-03-en-surface.png",
                    "helios-04-lame-michel-illustration.png",
                    "helios-05-dent-craker-illustration.png",
                    "helios-chassis-eprouves-helios.png",
                    "helios-degagement-sous-chassis-helios.png",
                    "helios-dent-craker-1.png",
                    "helios-dent-craker-2.png",
                    "helios-dent-craker-3.png",
                    "helios-dent-craker-eclatee.png",
                    "helios-ecartement-entre-dent-helios.png",
                    "helios-duo-60.png",
                    "helios-duo-70.png",
                    "helios-helios-carker-60.png",
                    "helios-helios-craker-70.png",
                    "helios-helios-craker-80.png",
                    "helios-helios-duo-80.png",
                    "helios-helios-duo-t80.png",
                    "helios-helios-duo-t90.png",
                    "helios-helios-mono-60.png",
                    "helios-helios-mono-70.png",
                    "helios-lame-michel-eclatee.png",
                    "helios-lame-michel.png",
                    "helios-quechoisir-craker.png",
                    "helios-quechoisir-duo.png",
                    "helios-quechoisir-mono.png",
                    "helios-securite-boulon-craker.png",
                    "helios-securite-boulon-helios-craker-1.png",
                    "helios-securite-boulon-helios-craker-2-1.png",
                    "helios-securite-boulon-helios-craker-2.png",
                    "helios-securite-boulon-helios-craker-2-2.png",
                    "helios-securite-boulon-mono.png",
                    "helios-securite-boulon-traction-craker.png",
                    "helios-securite-hydraulique-mono.png",
                    "helios-securite-hydraulique-renforcee-semi-portes-duo.png",
                    "normandie-disque-normandie-1.png",
                    "normandie-disque-normandie-2.png",
                    "normandie-disque-normandie-3.png",
                    "normandie-disque-normandie-4.png",
                    "normandie-normandie-40.png",
                    "normandie-normandie-50.png",
                    "normandie-normandie-60.png",
                    "normandie-normandie-70.png",
                    "normandie-normandie-t60.png",
                    "normandie-normandie-t70.png",
                    "normandie-normandie-t80-12m.png",
                    "normandie-securite-angle-attaque.png",
                    "normandie-securite-angle-entrure.png",
                    "normandie-securite-non-stop-elastomere-1.png",
                    "normandie-securite-non-stop-elastomere-2.png",
                    "prima-40.png",
                    "prima-50.png",
                    "prima-70.png",
                    "prima-80.png",
                    "prima-ajout-retrait-corps.png",
                    "prima-attelage-epure-1.png",
                    "prima-attelage-epure-2.png",
                    "prima-attelage-epure-3.png",
                    "prima-attelage-epure-4.png",
                    "prima-attelage-epure-5.png",
                    "prima-caisson-robuste.png",
                    "prima-corps-a-barre.png",
                    "prima-corps-a-pointe.png",
                    "prima-deport-sur-prima-1.png",
                    "prima-deport-sur-prima-2.png",
                    "prima-divers-prima.png",
                    "prima-realignement-hydraulique.png",
                    "prima-reglage-multipositions.png",
                    "prima-reglage-simple-ok.png",
                    "prima-suspension-prima.png",
                    "rouleau_impak_decrottoir-actif-arriere.png",
                    "rouleau-andpak-2.png",
                    "rouleau-andpak.png",
                    "rouleau-barre.png",
                    "rouleau-barres-carees-sol.png",
                    "rouleau-barres-carrees.png",
                    "rouleau-barres-rondes-illustration.png",
                    "rouleau-barres-rondes.png",
                    "rouleau-crosskill-2.png",
                    "rouleau-crosskill.png",
                    "rouleau-double-pics-sol.png",
                    "rouleau-double-pics.png",
                    "rouleau-double-rouleau-barres-carrees.png",
                    "rouleau-double-rouleau-crenele-sol.png",
                    "rouleau-double-rouleaux-crenele.png",
                    "rouleau-double.png",
                    "rouleau-doubles-barres-carrees.png",
                    "rouleau-emopack-v.png",
                    "rouleau-emopak-plat-2.png",
                    "rouleau-emopak-plat.png",
                    "rouleau-herse-peigne-triple.png",
                    "rouleau-herse-peigne.png",
                    "rouleau-impak-partie-centrale.png",
                    "rouleau-impak.png",
                    "rouleau-packer.png",
                    "rouleau-rotoherse-1.png",
                    "rouleau-rotoherse-2.png",
                    "rouleau-rotoherse.png",
                    "rouleau-transpak.png",
                    "rouleau-twin-sol.png",
                    "rouleau-twin.png",
                    "rover-50.png",
                    "rover-60.png",
                    "rover-70.png",
                    "rover-80.png",
                    "rover-accumulateur-pression.png",
                    "rover-ajout-retrait-corps-rover-1.png",
                    "rover-ajout-retrait-corps-rover-2.png",
                    "rover-andpak-illustration.png",
                    "rover-aplomb-hydraulique-rover-1.png",
                    "rover-aplomb-hydraulique-rover-2.png",
                    "rover-aplomb-mecanique-rover.png",
                    "rover-caisson-double-rover-1.png",
                    "rover-caisson-double-rover-2.png",
                    "rover-caisson-z-rover.png",
                    "rover-capot-de-protection-rover.png",
                    "rover-deport-devert-rover.png",
                    "rover-dimensions-compactes-rover.png",
                    "rover-fusees-robustes-rover.png",
                    "rover-multi-positions-rover.png",
                    "rover-suspension-du-3e-point-rover.png",
                    "rover-varilage-rover.png",
                    "tetra-50-v2.png",
                    "tetra-50.png",
                    "tetra-60-450m.png",
                    "tetra-60-600m.png",
                    "tetra-70.png",
                    "tetra-80-lame-nivelleuse-reglable.png",
                    "tetra-80-zoom-1.png",
                    "tetra-80-zoom-2.png",
                    "tetra-80-zoom-3.png",
                    "tetra-80-zoom-4.png",
                    "tetra-80-zoom-5.png",
                    "tetra-80-zoom-6.png",
                    "tetra-80.png",
                    "tetra-450-profil-droit.png",
                    "tetra-450-profil-s.png",
                    "tetra-600-profil-droit.png",
                    "tetra-600-profil-s.png",
                    "tetra-efface-trace-patte--sans-ombre.png",
                    "tetra-efface-trace-patte-oie-ombre.png",
                    "tetra-efface-trace-soc-fonte-pas-ombre-possible.png",
                    "tetra-rouleau-sans-entretien.png",
                    "voyager-accidents-climatiques-illustration.png",
                    "voyager-avant-train-articulable-voyager.png",
                    "voyager-caisson-z-voyager.png",
                    "voyager-chariot-voyager.png",
                    "voyager-compensation-report-charge.png",
                    "voyager-corps-additionnel-voyager.png",
                    "voyager-deport-voyager.png",
                    "voyager-desherbage-illustration.png",
                    "voyager-eau-stagnante-illustration.png",
                    "voyager-enfouissement-illustration.png",
                    "voyager-mineralisation-illustration.png",
                    "voyager-mono-roue-voyager.png",
                    "voyager-multi-position-voyager.png",
                    "voyager-orientation-charrue-voyager.png",
                    "voyager-reglages-simples-voyager.png",
                    "voyager-relevage-arriere-voyager.png",
                    "voyager-retournement-souple-voyager-1.png",
                    "voyager-retournement-souple-voyager-2.png",
                    "voyager-structure-sol-illustration.png",
                    "voyager-transpak-illustration.png",
                    "voyager-varilarge-voyager.png",
                    "voyager-voyager-c60.png",
                    "voyager-voyager-c80.png",
                    "voyager-voyager-s60.png",
                    "voyager-voyager-s70.png"
                    );
                    foreach ($arr as $value) {
                        echo "
                        <div class=\"col-3\">\n
                            <div class=\"card\" style=\"margin-bottom: 2rem;\">\n
                                <div class=\"ratio\" style=\"background-image: url(https://marketing.cellar.services.clever-cloud.com/photos/gregoire-besson/small/".$value.");\"></div>\n
                                <p class=\"text-center\" style=\"margin: 0; padding: 0.5rem; font-size:0.7rem;\"><small>".$value."</small></p>
                                <a class=\"text-center\" href=\"https://marketing.cellar.services.clever-cloud.com/photos/gregoire-besson/original/".$value."\" download target=\"_blank\"><small style=\"font-weight: bold; padding-bottom: 0.5rem; display: block;\">Download &darr;</small></a>\n
                            </div>\n
                        </div>\n
                        \n
                        ";}
                    ?>
                </div>
            </div>    
        </div>
    </div>
    
  </body>
</html>